// AUTO-GENERATED by scripts/emit-jp-internal-links.js — do not hand-edit.
// Role pages that exist under each job-placement industry, used to build
// hub -> spoke internal links on the industry hub pages. City spokes come
// from jpMetros in ./jpGridData.

export type JpRole = { slug: string; name: string };

export const jpRolesByIndustry: Record<string, JpRole[]> = {
  "accounting-cpa": [
    {
      "slug": "accounting-manager",
      "name": "Accounting Manager"
    },
    {
      "slug": "audit-manager",
      "name": "Audit Manager"
    },
    {
      "slug": "cfo",
      "name": "CFO"
    },
    {
      "slug": "controller",
      "name": "Controller"
    },
    {
      "slug": "senior-accountant",
      "name": "Senior Accountant"
    },
    {
      "slug": "tax-manager",
      "name": "Tax Manager"
    }
  ],
  "architecture": [
    {
      "slug": "bim-manager",
      "name": "BIM Manager"
    },
    {
      "slug": "design-director",
      "name": "Design Director"
    },
    {
      "slug": "principal",
      "name": "Principal"
    },
    {
      "slug": "project-architect",
      "name": "Project Architect"
    },
    {
      "slug": "project-manager",
      "name": "Architecture Project Manager"
    }
  ],
  "banking": [
    {
      "slug": "branch-manager",
      "name": "Branch Manager"
    },
    {
      "slug": "commercial-lender",
      "name": "Commercial Lender"
    },
    {
      "slug": "compliance-officer",
      "name": "Compliance Officer"
    },
    {
      "slug": "credit-analyst",
      "name": "Credit Analyst"
    },
    {
      "slug": "wealth-advisor",
      "name": "Wealth Advisor"
    }
  ],
  "biotech": [
    {
      "slug": "clinical-research-associate",
      "name": "Clinical Research Associate"
    },
    {
      "slug": "medical-affairs",
      "name": "Medical Affairs Lead"
    },
    {
      "slug": "qa-manager",
      "name": "QA Manager"
    },
    {
      "slug": "regulatory-affairs-manager",
      "name": "Regulatory Affairs Manager"
    },
    {
      "slug": "scientist",
      "name": "Scientist"
    }
  ],
  "construction-management": [
    {
      "slug": "assistant-project-manager",
      "name": "Assistant Project Manager"
    },
    {
      "slug": "estimator",
      "name": "Estimator"
    },
    {
      "slug": "preconstruction-manager",
      "name": "Preconstruction Manager"
    },
    {
      "slug": "project-executive",
      "name": "Project Executive"
    },
    {
      "slug": "project-manager",
      "name": "Construction Project Manager"
    },
    {
      "slug": "superintendent",
      "name": "Superintendent"
    }
  ],
  "cybersecurity": [
    {
      "slug": "ciso",
      "name": "CISO"
    },
    {
      "slug": "grc-analyst",
      "name": "GRC Analyst"
    },
    {
      "slug": "penetration-tester",
      "name": "Penetration Tester"
    },
    {
      "slug": "security-architect",
      "name": "Security Architect"
    },
    {
      "slug": "security-engineer",
      "name": "Security Engineer"
    },
    {
      "slug": "soc-analyst",
      "name": "SOC Analyst"
    }
  ],
  "dental": [
    {
      "slug": "associate-dentist",
      "name": "Associate Dentist"
    },
    {
      "slug": "dental-specialist",
      "name": "Dental Specialist"
    },
    {
      "slug": "hygienist-lead",
      "name": "Lead Hygienist"
    },
    {
      "slug": "practice-manager",
      "name": "Practice Manager"
    },
    {
      "slug": "treatment-coordinator",
      "name": "Treatment Coordinator"
    }
  ],
  "energy": [
    {
      "slug": "field-engineer",
      "name": "Field Engineer"
    },
    {
      "slug": "hse-manager",
      "name": "HSE Manager"
    },
    {
      "slug": "operations-manager",
      "name": "Operations Manager"
    },
    {
      "slug": "plant-supervisor",
      "name": "Plant Supervisor"
    },
    {
      "slug": "project-manager",
      "name": "Energy Project Manager"
    }
  ],
  "engineering": [
    {
      "slug": "design-engineer",
      "name": "Design Engineer"
    },
    {
      "slug": "electrical-engineer",
      "name": "Electrical Engineer"
    },
    {
      "slug": "engineering-manager",
      "name": "Engineering Manager"
    },
    {
      "slug": "mechanical-engineer",
      "name": "Mechanical Engineer"
    },
    {
      "slug": "project-engineer",
      "name": "Project Engineer"
    }
  ],
  "executive": [
    {
      "slug": "chief-executive-officer",
      "name": "Chief Executive Officer"
    },
    {
      "slug": "chief-financial-officer",
      "name": "Chief Financial Officer"
    },
    {
      "slug": "chief-operating-officer",
      "name": "Chief Operating Officer"
    },
    {
      "slug": "general-manager",
      "name": "General Manager"
    },
    {
      "slug": "vp-operations",
      "name": "VP of Operations"
    }
  ],
  "finance": [
    {
      "slug": "finance-manager",
      "name": "Finance Manager"
    },
    {
      "slug": "financial-analyst",
      "name": "Financial Analyst"
    },
    {
      "slug": "fpa-manager",
      "name": "FP&A Manager"
    },
    {
      "slug": "treasury-manager",
      "name": "Treasury Manager"
    },
    {
      "slug": "vp-finance",
      "name": "VP of Finance"
    }
  ],
  "government": [
    {
      "slug": "compliance-officer",
      "name": "Compliance Officer"
    },
    {
      "slug": "contracts-manager",
      "name": "Contracts Manager"
    },
    {
      "slug": "grants-manager",
      "name": "Grants Manager"
    },
    {
      "slug": "operations-director",
      "name": "Operations Director"
    },
    {
      "slug": "program-manager",
      "name": "Program Manager"
    }
  ],
  "healthcare": [
    {
      "slug": "clinical-director",
      "name": "Clinical Director"
    },
    {
      "slug": "nurse-practitioner",
      "name": "Nurse Practitioner"
    },
    {
      "slug": "physician",
      "name": "Physician"
    },
    {
      "slug": "physician-assistant",
      "name": "Physician Assistant"
    },
    {
      "slug": "registered-nurse",
      "name": "Registered Nurse"
    }
  ],
  "hospitality": [
    {
      "slug": "executive-chef",
      "name": "Executive Chef"
    },
    {
      "slug": "food-and-beverage-director",
      "name": "Food and Beverage Director"
    },
    {
      "slug": "general-manager",
      "name": "General Manager"
    },
    {
      "slug": "operations-manager",
      "name": "Hospitality Operations Manager"
    },
    {
      "slug": "revenue-manager",
      "name": "Revenue Manager"
    }
  ],
  "hr": [
    {
      "slug": "chro",
      "name": "CHRO"
    },
    {
      "slug": "hr-business-partner",
      "name": "HR Business Partner"
    },
    {
      "slug": "hr-director",
      "name": "HR Director"
    },
    {
      "slug": "hr-manager",
      "name": "HR Manager"
    },
    {
      "slug": "people-operations-manager",
      "name": "People Operations Manager"
    },
    {
      "slug": "talent-acquisition-manager",
      "name": "Talent Acquisition Manager"
    }
  ],
  "insurance": [
    {
      "slug": "account-manager",
      "name": "Insurance Account Manager"
    },
    {
      "slug": "actuary",
      "name": "Actuary"
    },
    {
      "slug": "claims-manager",
      "name": "Claims Manager"
    },
    {
      "slug": "commercial-lines-underwriter",
      "name": "Commercial Lines Underwriter"
    },
    {
      "slug": "producer",
      "name": "Insurance Producer"
    },
    {
      "slug": "risk-manager",
      "name": "Risk Manager"
    }
  ],
  "legal": [
    {
      "slug": "general-counsel",
      "name": "General Counsel"
    },
    {
      "slug": "litigation-associate",
      "name": "Litigation Associate"
    },
    {
      "slug": "paralegal",
      "name": "Paralegal"
    },
    {
      "slug": "partner",
      "name": "Lateral Partner"
    }
  ],
  "manufacturing": [
    {
      "slug": "operations-director",
      "name": "Operations Director"
    },
    {
      "slug": "plant-manager",
      "name": "Plant Manager"
    },
    {
      "slug": "process-engineer",
      "name": "Process Engineer"
    },
    {
      "slug": "quality-manager",
      "name": "Quality Manager"
    },
    {
      "slug": "supply-chain-manager",
      "name": "Supply Chain Manager"
    }
  ],
  "marketing": [
    {
      "slug": "brand-manager",
      "name": "Brand Manager"
    },
    {
      "slug": "content-lead",
      "name": "Content Lead"
    },
    {
      "slug": "demand-gen-manager",
      "name": "Demand Generation Manager"
    },
    {
      "slug": "growth-marketer",
      "name": "Growth Marketer"
    },
    {
      "slug": "marketing-director",
      "name": "Marketing Director"
    }
  ],
  "nonprofit": [
    {
      "slug": "development-director",
      "name": "Development Director"
    },
    {
      "slug": "executive-director",
      "name": "Executive Director"
    },
    {
      "slug": "finance-director",
      "name": "Nonprofit Finance Director"
    },
    {
      "slug": "major-gifts-officer",
      "name": "Major Gifts Officer"
    },
    {
      "slug": "program-director",
      "name": "Program Director"
    }
  ],
  "real-estate": [
    {
      "slug": "asset-manager",
      "name": "Asset Manager"
    },
    {
      "slug": "commercial-broker",
      "name": "Commercial Broker"
    },
    {
      "slug": "facilities-manager",
      "name": "Facilities Manager"
    },
    {
      "slug": "leasing-director",
      "name": "Leasing Director"
    },
    {
      "slug": "property-manager",
      "name": "Property Manager"
    }
  ],
  "sales": [
    {
      "slug": "account-executive",
      "name": "Account Executive"
    },
    {
      "slug": "enterprise-account-executive",
      "name": "Enterprise Account Executive"
    },
    {
      "slug": "sales-director",
      "name": "Sales Director"
    },
    {
      "slug": "sales-engineer",
      "name": "Sales Engineer"
    },
    {
      "slug": "sdr-manager",
      "name": "SDR Manager"
    },
    {
      "slug": "vp-sales",
      "name": "VP of Sales"
    }
  ],
  "supply-chain": [
    {
      "slug": "demand-planner",
      "name": "Demand Planner"
    },
    {
      "slug": "logistics-manager",
      "name": "Logistics Manager"
    },
    {
      "slug": "operations-manager",
      "name": "Operations Manager"
    },
    {
      "slug": "procurement-manager",
      "name": "Procurement Manager"
    },
    {
      "slug": "supply-chain-manager",
      "name": "Supply Chain Manager"
    }
  ],
  "technology": [
    {
      "slug": "data-scientist",
      "name": "Data Scientist"
    },
    {
      "slug": "devops-engineer",
      "name": "DevOps Engineer"
    },
    {
      "slug": "engineering-manager",
      "name": "Engineering Manager"
    },
    {
      "slug": "senior-software-engineer",
      "name": "Senior Software Engineer"
    },
    {
      "slug": "software-engineer",
      "name": "Software Engineer"
    }
  ],
  "trades": [
    {
      "slug": "electrician",
      "name": "Electrician"
    },
    {
      "slug": "hvac-technician",
      "name": "HVAC Technician"
    },
    {
      "slug": "maintenance-technician",
      "name": "Maintenance Technician"
    },
    {
      "slug": "plant-supervisor",
      "name": "Plant Supervisor"
    },
    {
      "slug": "production-supervisor",
      "name": "Production Supervisor"
    }
  ],
  "veterinary": [
    {
      "slug": "associate-veterinarian",
      "name": "Associate Veterinarian"
    },
    {
      "slug": "hospital-director",
      "name": "Hospital Director"
    },
    {
      "slug": "lead-technician",
      "name": "Lead Veterinary Technician"
    },
    {
      "slug": "practice-manager",
      "name": "Practice Manager"
    },
    {
      "slug": "veterinary-specialist",
      "name": "Veterinary Specialist"
    }
  ]
};
